<?php

$labels = array();
$labels['forgotpassword'] = 'Забыли пароль?';
$labels['passwordrecovery'] = 'Forgot Password';
$labels['email_subject'] = 'Сброс почтового пароля';
$labels['admin_alert_email_subject'] = 'Запрос на сброс пароля';
$labels['pwreminder'] = 'Напоминание о пароле';
$labels['forgot_passwordform'] = 'Форма сброса пароля.';
$labels['forgot_passwordenabled'] = 'Включено';
$labels['forgot_passwordisenabled'] = 'Напоминание включено';
$labels['forgot_passworddisabled'] = 'Напоминание отключено';
$labels['forgot_passwordaddress'] = 'Куда отправить пароль';
$labels['forgot_passwordquestion'] = 'Секретный вопрос';
$labels['forgot_passwordanswer'] = 'Ответ на секретный вопрос';
$labels['forgot_passwordanswerconfirm'] = 'Подтвердить ответ';
$labels['forgot_passwordaddidentity'] = 'Пожалуйста, настройте ваш профиль';
$labels['forgot_passwordadd'] = 'добавить';
$labels['forgot_passwordresetpw'] = 'Подтвердить';
$labels['forgot_passwordexit'] = 'Отмена';
$labels['new_password'] = 'Новый пароль';
$labels['new_password_confirmation'] = 'Подтверждение';
$labels['no_alternative_email_warning'] = 'Введите дополнительный адрес электронной почты.';
$labels['click_here'] = 'Щелкните здесь';
$labels['recovery_email'] = 'восстановление электронной почты';
$labels['save'] = 'Сохранить';

$messages = array();
$messages['forgot_passwordquestionempty'] = 'Введите Ваш секретный вопрос';
$messages['forgot_passworduserempty'] = 'Введите Ваш адрес электронной почты';
$messages['forgot_passwordanswerempty'] = 'Введите Ваш ответ на секретный вопрос';
$messages['forgot_passwordanswernotmatch'] = 'Ответ на секретный вопрос не верный';
$messages['forgot_passwordactive'] = 'Напоминание пароля будет включено';
$messages['forgot_passwordinactive'] = 'Напоминание пароля отключено';
$messages['forgot_passwordusernotfound'] ='Пользователь не найден';
$messages['forgot_passwordimcomplete'] ='Настройка напоминания пароля не выполнена. Свяжитесь с <a href=mailto:admin@arcticsu.ru>системным администратором</a>.';
$messages['forgot_passwordfailed'] = 'Ответ на секретный вопрос не верный';
$messages['sendingfailed'] = 'Ошибка при отправке инструкций по сбросу пароля. Попробуйте еще раз позже.';
$messages['checkaccount'] = 'Инструкции по сбросу пароля отправлены на Ваш дополнительный адрес электронной почты.';
$messages['senttoadmin'] = 'В вашем профиле не найден настроенный дополнительный адрес электронной почты, поэтому Ваш запрос был передан системному администратору.';
$messages['autobanned'] = 'Доступ временно заблокирован (слишком много неудачных попыток войти). Пожалуйста, попробуйте еще раз позже или обратитесь к <a href=mailto:admin@arcticsu.ru>системному администратору</a>.';
$messages['nodeleteforgot_passwordaddress'] = 'К этому профилю привязано напоминание о пароле.';
$messages['invalidtoken'] = 'Неверный токен';
$messages['password_confirmation_invalid'] = 'Неверный пароль';
$messages['password_weakness_check_failed'] = 'Ошибка. Слишком простой пароль!';
$messages['password_changed'] = 'Пароль успешно изменен!';
$messages['password_not_changed'] = 'Произошла ошибка при изменении вашего пароля. Попробуйте еще раз позже или обратитесь к <a href=mailto:admin@arcticsu.ru>системному администратору</a>.';
$messages['notice_no_alternative_email_warning'] = 'У Вас не настроен дополнительный адрес электронной почты. %s и настройте!';
$messages['alternative_email_updated'] = 'Дополнительный адрес электронной почты настроен.';
$messages['alternative_email_invalid'] = 'Введите правильный адрес электронной почты!';
?>

